# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Udari's Kitchen
subtitle: "Discover the Essence of Sri Lanka: Flavors, Spices, and Tradition"
email: mahishizu@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  Dive into the world of culinary arts with Savory Delights, where every recipe is crafted to bring joy to your kitchen. Whether you're a seasoned chef or a home cook, our blog offers a wide array of recipes, cooking tips, and kitchen hacks to inspire and elevate your cooking game.
  From mouth-watering appetizers to decadent desserts, discover step-by-step guides that make cooking approachable and fun. Explore international cuisines, learn the secrets of perfect baking, and find healthy meal ideas for every occasion. With stunning photos and detailed instructions, our goal is to make cooking a delightful and rewarding experience for everyone.
  Join our community of food lovers, share your culinary creations, and let's embark on this delicious journey together. Happy cooking!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://udarikitchen.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  udarikitchen

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

atom_feed:
  hide: true
search: true # true, false (default)
search_full_content: true # true, false (default)
google:
  search_engine_id: 758eb3977da6545cd # YOUR_SEARCH_ENGINE_ID
  instant_search: true # false (default), true
# SEO Related
google_site_verification: rNGH6FZfpFYg_00XlqkFy6O3Wr_Slo04IVVJC7-iKyI
plugins:
  - jekyll-include-cache
name: &name "Mahishi Udari"
description: &description "Embark on a culinary adventure through the vibrant flavors and rich heritage of Sri Lankan cooking with Spice of Ceylon. Our blog is your ultimate destination for discovering the diverse and exotic dishes that make Sri Lankan cuisine truly unique."
author:
  name: *name # *name is a YAML reference pointing to the &anchor earlier
  avatar: "/assets/images/mahishi-udari.png"
  bio: "From My Kitchen to Yours: Heartfelt Recipes for Home Cooking"
  location: "Sydney, Australia"
  links:
    - label: "Udaris Kitchen"
      icon: "fas fa-fw fa-link"
      url: "https://udarikitchen.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/udarikitchen/udarikitchen.github.io"
# Social Sharing
facebook:
  username               : &facebook "mahishi.udari"
  app_id                 :
  publisher              :

# Site Footer
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/mahishi.udari
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/udarikitchen/udarikitchen.github.io


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Australia/Sydney # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      read_time: true
      comments: true
      share: true
      related: true